//DO NOT EDIT THIS FILE.
//Generated by go-validation

package models

type ValidationError struct {
	Field string
	Err   error
}

func (v User) Validate() ([]ValidationError, error) {
var resError []ValidationError
var err error
	if len(v.ID) < 36 {
	resError = append(resError, ValidationError{Field: v.ID, Err: errors.New("field lenght validation error"),})
	}